import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Bob',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Painting of Laura",
      category: "Painting",
      image: '/images/Laura.png',
      price: "100",
      countInStock: 10,
      brand: "Garrett's Artwork",
      rating: "4.4",
      numReviews: "10",
      description: '1st iteration of painting',
    },
    {
      name: "Painting of Claire",
      category: "Painting",
      image: "/images/Claire.png",
      price: "80",
      countInStock: 20,
      brand: "Garrett's Artwork",
      rating: "4.0",
      numReviews: "10",
      description: '1st iteration of drawing of Rachel',
    },
    {
      name: "Painting of Riley",
      category: "Painting",
      image: "/images/Riley.jpeg",
      price: "90",
      countInStock: 0,
      brand: "Garrett's Artwork",
      rating: "4.3",
      numReviews: "100",
      description: '1st iteration of painting',
    },
    {
      name: "Woman Portrait #1",
      category: "Painting",
      image: "/images/womanportrait1.png",
      price: "95",
      countInStock: 15,
      brand: "Garrett's Artwork",
      rating: "4.1",
      numReviews: "20",
      description: '1st iteration of painting',
    },
    {
      name: "Woman Portrait #2",
      category: "Painting",
      image: "/images/womanportrait2.png",
      price: "110",
      countInStock: 5,
      brand: "Garrett's Artwork",
      rating: "4.3",
      numReviews: "90",
      description: '1st iteration of painting',
    },
    {
      name: "Woman Portrait #3",
      category: "Painting",
      image: "/images/womanportrait3.png",
      price: "120",
      countInStock: 12,
      brand: "Garrett's Artwork",
      rating: "4.3",
      numReviews: "50",
      description: '1st iteration of painting',
    },
  ],
}
export default data;